In [6]:
import numpy as np 

array = np.arange(11)

In [3]:
arra = np.arange(5)
print(arra)

[0 1 2 3 4]


In [4]:
# boolean array
np.full((3,3), True, dtype=bool)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
import numpy as np
array = np.array([1,2,3])
print("ARRAY 1D: \n")
print(array)

ARRAY 1D: 

[1 2 3]


In [5]:
array2 = np.array([(1,2,3),(4,5,6)])
print("ARRAY 2D: \n")
print(array2)

ARRAY 2D: 

[[1 2 3]
 [4 5 6]]


In [7]:
r= array * array2
print(r)

[[ 1  4  9]
 [ 4 10 18]]


In [6]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print("1: \n")
print(a)
print("2: \n")
print(b)

1: 

[[0 1 2 3 4]
 [5 6 7 8 9]]
2: 

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
import numpy as np
import time 

SIZE = 1000000

l1= range(SIZE)
l2= range(SIZE)
A1= np.arange(SIZE)
A2= np.arange(SIZE)

start = time.time()
result = [(x,y) for x,y in zip(l1,l2)]
print("Resultado lista de python: \n")
print((time.time()-start)*1000)
print()
start=time.time()
result = A1+A2
print("Resultado Numpy array: \n")
print((time.time()-start)*1000)
#se ve ek tiempo en el que sera mas facil usar matrices

Resultado lista de python: 

270.84898948669434

Resultado Numpy array: 

80.01160621643066


In [11]:
#Crear matrices llena de unos 
unos= np.ones((3,4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
#matrix igual a cero
ceros= np.zeros((3,4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
#matrix con numeros aleatoreos
ale = np.random.random((2,2))
print(ale)

[[0.02515053 0.53291829]
 [0.62975461 0.34111517]]


In [15]:
#crear matriz vacia 
vacia = np.empty((3,2))
print(vacia)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [16]:
#matriz con un solo valor en toda la matriz 
full = np.full((2,2),8)
print(full)

[[8 8]
 [8 8]]


In [17]:
#crear matrices con valores espaciados uniformemente 
espacio1 = np.arange(0,30,5)
print(espacio1) 
espacio2= np.linspace(0,2,5)
print(espacio2)

[ 0  5 10 15 20 25]
[0.  0.5 1.  1.5 2. ]


In [19]:
#matrix identidad 
identidad1= np.eye(2,2)
print(identidad1)
identidad2= np.identity(4)
print(identidad2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
#inspeccionar Matrices 
#conocer las dimenciones de una matrix
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


In [22]:
#conocer el tipo de datos de una matrix
a= np.array([(1,2,3)])
print(a.dtype)

int32


In [23]:
#tamaño y forma de la matrix
a= np.array ([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


In [25]:
#cambio de forma de una matriz
a=np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [26]:
#Extraer un elemento
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [27]:
#extraer los valores de todas las filas ubicados en la columna 3 
a= np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])

[3 5]


In [29]:
#operaciones matematicas
#minumo maximo en una matriz
a = np.array([2,4,8])
print("El minimo es: \n",a.min())
print("El maximo es: \n",a.max())
print("La suma es: \n",a.sum())

El minimo es: 
 2
El maximo es: 
 8
La suma es: 
 14


In [31]:
#calcular la raiz cuadrada y la desviacion estandar 
a= np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))
print(np.std(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056
